server:
  host: localhost
  port: 8443

logging:
  level:
    de.focus_shift.impl.DefaultHolidayManager: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reggio
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

